backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Sección", name: "section", widget: "select", options: ["Opinión", "Humor", "Deportes", "Noticias"]}
      - {label: "Etiquetas", name: "tags", widget: "list"}
      - {label: "Imagen destacada", name: "featured_image", widget: "image"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}